[package]
name = "mcc-agent"
description = "MicroCommandControl node agent"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
mcc-api = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "time"] }
tracing = { workspace = true }
tonic = { version = "0.12", features = ["transport", "tls", "tls-roots"] }
http = "1"
num_cpus = "1"

[lib]
name = "mcc_agent"
path = "src/lib.rs"
