//! Interactive setup wizard: two trees — **Server** (run on the VPS) and
//! **Client** (run locally to connect).
//!
//! The wizard only scaffolds config and prints instructions; it never starts
//! the server or Traefik (BYO Traefik, "one process" philosophy). Core logic
//! is pure and unit-tested; interactive prompts live behind [`crate::prompt`].

use crate::context;
use crate::prompt;
use anyhow::{bail, Context, Result};
use std::path::{Path, PathBuf};

pub const DEFAULT_BIND: &str = "127.0.0.1:7443";
pub const DEFAULT_DATA_DIR: &str = "~/.mc2";
pub const DEFAULT_INGRESS_DIR: &str = "~/.mc2/ingress";
pub const DEFAULT_RESOLVER: &str = "le";

/// Everything the server tree collects.
#[derive(Debug, Clone)]
pub struct ServerPlan {
    pub data_dir: PathBuf,
    pub bind: String,
    pub auth_enabled: bool,
    /// Set when the operator accepted unauthenticated remote access
    /// (`--no-auth` on a non-loopback bind).
    pub allow_unauthenticated_remote: bool,
    pub public_hostname: Option<String>,
    pub tls_cert_resolver: String,
    pub ingress_dir: PathBuf,
    pub write_traefik: bool,
    pub acme_email: Option<String>,
}

impl ServerPlan {
    /// Absolute path of the generated Traefik static config.
    pub fn traefik_static_path(&self) -> PathBuf {
        self.ingress_dir
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join("traefik.static.yml")
    }
}

/// Everything the client tree collects.
#[derive(Debug, Clone)]
pub struct ClientPlan {
    pub name: String,
    pub url: String,
    pub token: String,
}

/// Render the `mc2 server …` command for the plan (copy-paste runnable).
pub fn render_server_command(p: &ServerPlan) -> String {
    let mut parts = vec!["mc2 server".to_string()];
    parts.push(format!(
        "  --data-dir {}",
        sh_quote(&p.data_dir.to_string_lossy())
    ));
    parts.push(format!("  --bind {}", p.bind));
    if !p.auth_enabled {
        parts.push("  --no-auth".to_string());
        if p.allow_unauthenticated_remote {
            parts.push("  --allow-unauthenticated-remote".to_string());
        }
    }
    parts.push(format!(
        "  --ingress-config-dir {}",
        sh_quote(&p.ingress_dir.to_string_lossy())
    ));
    if let Some(host) = &p.public_hostname {
        parts.push(format!("  --public-hostname {host}"));
        parts.push(format!(
            "  --public-tls-cert-resolver {}",
            p.tls_cert_resolver
        ));
    }
    parts.join(" \\\n")
}

/// Resolve the server wizard's auth answers into a runnable flag set.
///
/// * a public hostname always keeps auth on (never offer an open, published
///   control plane);
/// * a non-loopback bind needs the explicit escape hatch, else auth stays on.
pub fn resolve_auth_plan(
    bind: &str,
    has_public_hostname: bool,
    want_no_auth: bool,
    hatch: bool,
) -> (bool, bool) {
    if !want_no_auth || has_public_hostname {
        return (true, false);
    }
    if mc2_server::bind_is_loopback(bind) {
        return (false, false);
    }
    if hatch {
        (false, true)
    } else {
        (true, false)
    }
}

/// Write the default Traefik static config next to the ingress dir (once;
/// never clobbers an existing file). Returns `(path, wrote)` — `wrote` is
/// false when the file already existed.
pub fn write_traefik_static(p: &ServerPlan) -> Result<(PathBuf, bool)> {
    let path = p.traefik_static_path();
    if path.exists() {
        return Ok((path, false));
    }
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    std::fs::create_dir_all(parent).with_context(|| format!("mkdir {}", parent.display()))?;

    let email = p.acme_email.as_deref().unwrap_or("you@example.com");
    let acme_storage = parent.join("acme.json");
    let provider_dir = p.ingress_dir.join("traefik");
    let path_display = path.display();
    let acme_display = acme_storage.display();
    let provider_display = provider_dir.display();

    let content = format!(
        r#"# Generated by MC2 setup — operator-owned after this point (MC2 will not rewrite it).
# Start: traefik --configFile {path_display}
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  le:
    acme:
      email: {email}
      storage: {acme_display}
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: {provider_display}
    watch: true
"#
    );
    std::fs::write(&path, content).with_context(|| format!("write {}", path.display()))?;
    Ok((path, true))
}

/// Save a client context (upsert + current). Pure; used by tests.
///
/// An empty token (a `--no-auth` server) stores no `api_key`.
pub fn apply_client(p: &ClientPlan) -> Result<()> {
    let mut cfg = context::load()?;
    let entry = cfg
        .contexts
        .entry(p.name.clone())
        .or_insert_with(|| context::ContextEntry {
            url: String::new(),
            api_key: None,
        });
    entry.url = p.url.trim_end_matches('/').to_string();
    entry.api_key = if p.token.is_empty() {
        None
    } else {
        Some(p.token.clone())
    };
    cfg.set_current(&p.name)?;
    context::save(&cfg)?;
    println!("context '{}' set ({}) and made current", p.name, p.url);
    Ok(())
}

/// Live check against a control plane (health + auth). Returns a one-liner.
async fn verify_connection(p: &ClientPlan) -> Result<String> {
    let base = p.url.trim_end_matches('/');
    let client = reqwest::Client::new();
    let mut req = client.get(format!("{base}/v1/status"));
    if !p.token.is_empty() {
        req = req.bearer_auth(&p.token);
    }
    let res = req
        .send()
        .await
        .with_context(|| format!("GET {base}/v1/status"))?;
    let status = res.status();
    let body = res.text().await.unwrap_or_default();
    if !status.is_success() {
        bail!("connection check failed: {status}: {body}");
    }
    let v: serde_json::Value = serde_json::from_str(&body)?;
    let version = v["version"].as_str().unwrap_or("?");
    let hostname = v["publicHostname"].as_str().unwrap_or("");
    let host = if hostname.is_empty() {
        String::new()
    } else {
        format!(" (public hostname {hostname})")
    };
    Ok(format!("connected: mc2 {version} at {base}{host}"))
}

/// Top-level wizard: pick Server or Client.
pub async fn run() -> Result<()> {
    prompt::ensure_tty()?;
    let choice = prompt::select(
        "What are you setting up?",
        &["Server (on the VPS)", "Client (connect to a server)"],
    )?;
    match choice {
        0 => run_server_wizard().await?,
        _ => run_client_wizard().await?,
    }
    Ok(())
}

/// Server tree: collect flags, scaffold the Traefik static config, print
/// the runnable command + finish-setup checklist.
pub async fn run_server_wizard() -> Result<()> {
    prompt::ensure_tty()?;

    let bind = prompt::input("Server bind address", DEFAULT_BIND, false)?;
    let data_dir_raw = prompt::input("Data directory", DEFAULT_DATA_DIR, false)?;
    let data_dir = mc2_server::expand_data_dir(&data_dir_raw);

    let public_hostname = prompt::input(
        "Public hostname for the control plane (Enter for local-only)",
        "",
        true,
    )?;
    let public_hostname = {
        let trimmed = public_hostname.trim();
        if trimmed.is_empty() {
            None
        } else {
            Some(trimmed.to_string())
        }
    };
    let tls_cert_resolver = if public_hostname.is_some() {
        prompt::input("TLS cert resolver (Traefik)", DEFAULT_RESOLVER, false)?
    } else {
        DEFAULT_RESOLVER.to_string()
    };

    // Auth: never offer to disable it when the control plane is published, and
    // ask about the escape hatch before emitting a command that would refuse.
    let want_no_auth = if public_hostname.is_some() {
        println!("note: auth stays on — --no-auth is not allowed with a public hostname.");
        false
    } else {
        !prompt::confirm("Protect the API with an API key?", true)?
    };
    let hatch = if want_no_auth && !mc2_server::bind_is_loopback(&bind) {
        prompt::confirm(
            "Bind is not loopback: allow unauthenticated remote access? \
             (--allow-unauthenticated-remote)",
            false,
        )?
    } else {
        false
    };
    let (auth_enabled, allow_unauthenticated_remote) =
        resolve_auth_plan(&bind, public_hostname.is_some(), want_no_auth, hatch);
    if want_no_auth && auth_enabled {
        println!(
            "note: --no-auth needs a loopback bind or \
             --allow-unauthenticated-remote; keeping auth on."
        );
    }

    let ingress_raw = prompt::input(
        "Ingress config dir (Traefik file catalog)",
        DEFAULT_INGRESS_DIR,
        false,
    )?;
    let ingress_dir = mc2_server::expand_data_dir(&ingress_raw);

    let write_traefik = if public_hostname.is_some() {
        prompt::confirm("Write a default traefik.static.yml?", true)?
    } else {
        false
    };
    let acme_email = if write_traefik {
        Some(prompt::input("ACME email (Let's Encrypt)", "", false)?)
    } else {
        None
    };

    let plan = ServerPlan {
        data_dir,
        bind,
        auth_enabled,
        allow_unauthenticated_remote,
        public_hostname,
        tls_cert_resolver,
        ingress_dir,
        write_traefik,
        acme_email,
    };
    print_server_plan(&plan)?;
    Ok(())
}

/// Client tree: gather URL + optional token, save the context, optionally verify.
pub async fn run_client_wizard() -> Result<()> {
    prompt::ensure_tty()?;

    let name = prompt::input("Context name", "prod", false)?;
    let url = prompt::input("Control plane URL", "https://mc2.example.com", false)?;
    let token = prompt::secret_optional("API token (Enter for a --no-auth server)")?;
    let verify = prompt::confirm("Verify the connection now?", true)?;

    let plan = ClientPlan { name, url, token };
    apply_client(&plan)?;
    if verify {
        match verify_connection(&plan).await {
            Ok(msg) => println!("{msg}"),
            Err(e) => println!("warning: could not verify — {e:#}"),
        }
    }
    println!("\nDone. Manage the server with `mc2 status`, `mc2 ps`, `mc2 apply …`.");
    Ok(())
}

/// Print the server plan as a runnable command + numbered checklist.
fn print_server_plan(p: &ServerPlan) -> Result<()> {
    let command = render_server_command(p);
    println!("== MC2 server setup ==");
    println!();
    println!("Run this to start the orchestrator:");
    println!();
    println!("{command}");
    println!();
    println!("Then finish the setup:");
    println!();
    println!("1. Start the server once to bootstrap. It creates the API token then:");
    println!("   - printed to the terminal (stderr) when that is a TTY, or");
    println!("   - written to <data-dir>/bootstrap-token (mode 0600) when it is not.");
    println!("   Save it; if you lose it, run `mc2 server token rotate --data-dir <dir>`.");
    if !p.auth_enabled {
        println!("   NOTE: `--no-auth` runs this start open (no bearer required). The token still");
        println!("   exists and can be rotated; auth returns on the next normal start.");
    }
    if p.write_traefik {
        let (path, wrote) = write_traefik_static(p)?;
        if wrote {
            println!("2. Start Traefik with the generated static config:");
        } else {
            println!("2. Start Traefik with the existing static config (left untouched):");
        }
        println!("   traefik --configFile {}", path.display());
        println!(
            "   (MC2 writes the dynamic routes under {}; Traefik watches them.)",
            p.ingress_dir.display()
        );
    } else {
        println!(
            "2. Point Traefik's file provider at {} and start it.",
            p.ingress_dir.join("traefik").display()
        );
    }
    if p.public_hostname.is_some() {
        println!(
            "3. Point DNS for {} at this host and open ports 80/443 (Let's Encrypt).",
            p.public_hostname.as_deref().unwrap_or("-")
        );
    } else {
        println!("3. (Local-only setup: no public hostname — the API stays on loopback.)");
    }
    println!("4. On your local machine run:");
    println!("   mc2 setup");
    println!("   …and choose \"Client\" to connect with the URL + API key.");
    println!();
    Ok(())
}

/// Quote a shell word (paths may contain spaces).
fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::context::with_home;

    fn plan(hostname: Option<&str>) -> ServerPlan {
        ServerPlan {
            data_dir: PathBuf::from("/srv/mc2"),
            bind: "127.0.0.1:7443".into(),
            auth_enabled: true,
            allow_unauthenticated_remote: false,
            public_hostname: hostname.map(str::to_string),
            tls_cert_resolver: "le".into(),
            ingress_dir: PathBuf::from("/srv/mc2/ingress"),
            write_traefik: true,
            acme_email: Some("ops@example.com".into()),
        }
    }

    #[test]
    fn server_command_includes_auth_and_self_ingress() {
        let cmd = render_server_command(&plan(Some("mc2.example.com")));
        assert!(cmd.starts_with("mc2 server"), "{cmd}");
        assert!(cmd.contains("--data-dir '/srv/mc2'"), "{cmd}");
        assert!(cmd.contains("--bind 127.0.0.1:7443"), "{cmd}");
        assert!(
            cmd.contains("--ingress-config-dir '/srv/mc2/ingress'"),
            "{cmd}"
        );
        assert!(cmd.contains("--public-hostname mc2.example.com"), "{cmd}");
        assert!(cmd.contains("--public-tls-cert-resolver le"), "{cmd}");
        assert!(!cmd.contains("--no-auth"), "auth on → no --no-auth: {cmd}");
    }

    #[test]
    fn server_command_local_only_and_no_auth() {
        let mut p = plan(None);
        p.auth_enabled = false;
        let cmd = render_server_command(&p);
        assert!(cmd.contains("--no-auth"), "{cmd}");
        assert!(!cmd.contains("--allow-unauthenticated-remote"), "{cmd}");
        assert!(!cmd.contains("--public-hostname"), "{cmd}");
        assert!(!cmd.contains("--public-tls-cert-resolver"), "{cmd}");
    }

    #[test]
    fn server_command_non_loopback_no_auth_includes_hatch() {
        let mut p = plan(None);
        p.bind = "0.0.0.0:7443".into();
        p.auth_enabled = false;
        p.allow_unauthenticated_remote = true;
        let cmd = render_server_command(&p);
        assert!(cmd.contains("--no-auth"), "{cmd}");
        assert!(cmd.contains("--allow-unauthenticated-remote"), "{cmd}");
    }

    #[test]
    fn auth_plan_never_disables_auth_with_public_hostname() {
        // Even with the hatch, a public hostname keeps auth on.
        assert_eq!(
            resolve_auth_plan("0.0.0.0:7443", true, true, true),
            (true, false)
        );
        assert_eq!(
            resolve_auth_plan("127.0.0.1:7443", true, true, false),
            (true, false)
        );
    }

    #[test]
    fn auth_plan_loopback_needs_no_hatch() {
        assert_eq!(
            resolve_auth_plan("127.0.0.1:7443", false, true, false),
            (false, false)
        );
        assert_eq!(
            resolve_auth_plan("localhost:7443", false, true, false),
            (false, false)
        );
    }

    #[test]
    fn auth_plan_non_loopback_needs_hatch() {
        // No hatch → auth stays on (the server would refuse to start otherwise).
        assert_eq!(
            resolve_auth_plan("0.0.0.0:7443", false, true, false),
            (true, false)
        );
        assert_eq!(
            resolve_auth_plan("0.0.0.0:7443", false, true, true),
            (false, true)
        );
    }

    #[test]
    fn auth_plan_keeps_auth_on_when_requested() {
        assert_eq!(
            resolve_auth_plan("0.0.0.0:7443", false, false, false),
            (true, false)
        );
    }

    #[test]
    fn apply_client_with_empty_token_stores_no_api_key() {
        let dir = tempfile::tempdir().unwrap();
        with_home(dir.path(), || {
            let plan = ClientPlan {
                name: "lab".into(),
                url: "http://127.0.0.1:7443".into(),
                token: String::new(),
            };
            apply_client(&plan).unwrap();
            let cfg = context::load().unwrap();
            assert_eq!(cfg.contexts["lab"].url, "http://127.0.0.1:7443");
            assert!(cfg.contexts["lab"].api_key.is_none());
        });
    }

    #[test]
    fn traefik_static_written_once_no_clobber() {
        let dir = tempfile::tempdir().unwrap();
        let mut p = plan(Some("mc2.example.com"));
        p.ingress_dir = dir.path().join("ingress");
        p.acme_email = Some("ops@example.com".into());

        let (path, wrote) = write_traefik_static(&p).unwrap();
        assert!(wrote);
        assert_eq!(path, dir.path().join("traefik.static.yml"));
        let first = std::fs::read_to_string(&path).unwrap();
        assert!(first.contains("address: \":80\""), "{first}");
        assert!(first.contains("address: \":443\""), "{first}");
        assert!(first.contains("certificatesResolvers:"), "{first}");
        assert!(first.contains("email: ops@example.com"), "{first}");
        assert!(first.contains("httpChallenge:"), "{first}");
        assert!(
            first.contains(&format!(
                "directory: {}",
                p.ingress_dir.join("traefik").display()
            )),
            "{first}"
        );

        // Second write must not clobber.
        let (_, wrote) = write_traefik_static(&p).unwrap();
        assert!(!wrote, "must not rewrite an existing static config");
        let second = std::fs::read_to_string(&path).unwrap();
        assert_eq!(
            first, second,
            "must not overwrite an existing static config"
        );
    }

    #[test]
    fn apply_client_upserts_and_sets_current() {
        let dir = tempfile::tempdir().unwrap();
        with_home(dir.path(), || {
            let plan = ClientPlan {
                name: "prod".into(),
                url: "https://mc2.example.com".into(),
                token: "mc2at_x".into(),
            };
            apply_client(&plan).unwrap();
            let cfg = context::load().unwrap();
            assert_eq!(cfg.current.as_deref(), Some("prod"));
            assert_eq!(cfg.contexts["prod"].url, "https://mc2.example.com");
            assert_eq!(cfg.contexts["prod"].api_key.as_deref(), Some("mc2at_x"));
        });
    }
}
